#ifndef TIMER1_CONFIG_H
#define TIMER1_CONFIG_H

/* Options for TIMER1_PRESCALER:
 * 1. TIMER1_NO_CLOCK
 * 2. TIMER1_PRESCALER_1
 * 3. TIMER1_PRESCALER_8
 * 4. TIMER1_PRESCALER_64
 * 5. TIMER1_PRESCALER_256
 * 6. TIMER1_PRESCALER_1024
 * 7. TIMER1_EXT_CLOCK_FALLING
 * 8. TIMER1_EXT_CLOCK_RISING
 */
#define TIMER1_PRESCALER    TIMER1_PRESCALER_8

#endif